name: 'Jirafy Changelog'
description: 'Generates a changelog from two references, where the markdown is formatted for any referenced Jira stories.'

inputs:
  githubToken:
    description: 'Your GITHUB_TOKEN'
    default: ''
    required: true
  head-ref:
    description: 'The name of the head reference'
    default: ''
    required: false
  base-ref:
    description: 'The name of the base reference'
    default: ''
    required: false
  jiraHost:
    description: 'Jira host name (i.e company.atlassian.net)'
    required: true

outputs:
  changelog:
    description: 'Markdown formatted changelog'

branding:
  icon: 'bell'
  color: 'blue'

runs:
  using: 'node12'
  main: 'dist/index.js'